from .DialogueTemplate import DialogueTemplate
# from .InputMisheardDialogueTemplate import InputMisheardDialogueTemplate
# from .PromptDialogueTemplate import  PromptDialogueTemplate
# from .PumpingGeneralDialogueTemplate import PumpingGeneralDialogueTemplate
from .UnknownDialogueTemplate import UnknownDialogueTemplate

from .FeedbackDialogueTemplate import FeedbackDialogueTemplate
from .HintingDialogueTemplate import HintingDialogueTemplate
from .InputMisheardDialogueTemplate import InputMisheardDialogueTemplate
from .PromptDialogueTemplate import PromptDialogueTemplate
from .PumpingGeneralDialogueTemplate import PumpingGeneralDialogueTemplate
from .PumpingSpecificDialogueTemplate import PumpingSpecificDialogueTemplate
from .ORSENWelcomeDialogueTemplate import ORSENWelcomeDialogueTemplate


from .DialogueHistoryTemplate import DialogueHistoryTemplate

"""EDEN"""
from .CPumpingDialogueTemplate import CPumpingDialogueTemplate
from .DCorrectingDialogueTemplate import DCorrectingDialogueTemplate
from .DPraiseDialogueTemplate import DPraiseDialogueTemplate
from .DPumpingDialogueTemplate import DPumpingDialogueTemplate
from .ELabelDialogueTemplate import ELabelDialogueTemplate
from .EPumpingDialogueTemplate import EPumpingDialogueTemplate
from .EvaluationDialogueTemplate import EvaluationDialogueTemplate
from .RecollectionDialogueTemplate import RecollectionDialogueTemplate
from .EEndDialogueTemplate import EEndDialogueTemplate
from .EEmphasisDialogueTemplate import EEmphasisDialogueTemplate
from .EDENWelcomeDialogueTemplate import EDENWelcomeDialogueTemplate
from .MClosingDialogueTemplate import MClosingDialogueTemplate
from .PPraiseDialogueTemplate import PPraiseDialogueTemplate
from .OReflectDialogueTemplate import OReflectDialogueTemplate
from .MFollowingDialogueTemplate import MFollowingDialogueTemplate
from .MIntroDialogueTemplate import MIntroDialogueTemplate
from .IFollowupDialogueTemplate import IFollowupDialogueTemplate
from .MWelcomeDialogueTemplate import MWelcomeDialogueTemplate
from .AcknowledgeDialogueTemplate import AcknowledgeDialogueTemplate
from .EFeedbackDialogueTemplate import EFeedbackDialogueTemplate
from .GPraiseDialogueTemplate import GPraiseDialogueTemplate
from .CounselingDialogueTemplate import CounselingDialogueTemplate
from .CFollowupDialogueTemplate import CFollowupDialogueTemplate
from .CFeedbackyDialogueTemplate import CFeedbackyDialogueTemplate
from .CFeedbacknDialogueTemplate import CFeedbacknDialogueTemplate
from .PReflectCareDialogueTemplate import PReflectCareDialogueTemplate
from .PReflectEnjoyDialogueTemplate import PReflectEnjoyDialogueTemplate
from .PReflectMusicDialogueTemplate import PReflectMusicDialogueTemplate
from .PReflectMusicF2DialogueTemplate import PReflectMusicF2DialogueTemplate
from .PReflectMusicPosDialogueTemplate import PReflectMusicPosDialogueTemplate
from .PReflectMusicNegDialogueTemplate import PReflectMusicNegDialogueTemplate
from .PReflectGratefulDialogueTemplate import PReflectGratefulDialogueTemplate
from .PReflectGratefulYesDialogueTemplate import PReflectGratefulYesDialogueTemplate
from .PReflectGratefulNoDialogueTemplate import PReflectGratefulNoDialogueTemplate
from .PReflectGratefulF2DialogueTemplate import PReflectGratefulF2DialogueTemplate
from .EReflectActivityDialogueTemplate import EReflectActivityDialogueTemplate
from .EReflectPastDialogueTemplate import EReflectPastDialogueTemplate
from .EReflectPastF2DialogueTemplate import EReflectPastF2DialogueTemplate
from .EReflectNatureDialogueTemplate import EReflectNatureDialogueTemplate
from .EReflectNature2DialogueTemplate import EReflectNature2DialogueTemplate
from .EReflectExcelDialogueTemplate import EReflectExcelDialogueTemplate
from .RReflectEnjoyDialogueTemplate import RReflectEnjoyDialogueTemplate
from .RReflectFriendDialogueTemplate import RReflectFriendDialogueTemplate
from .RReflectFriend2DialogueTemplate import RReflectFriend2DialogueTemplate
from .RReflectFriend2F2DialogueTemplate import RReflectFriend2F2DialogueTemplate
from .MReflectOrgDialogueTemplate import MReflectOrgDialogueTemplate
from .MReflectNewDialogueTemplate import MReflectNewDialogueTemplate
from .MReflectBoredDialogueTemplate import MReflectBoredDialogueTemplate
from .MReflectFriendDialogueTemplate import MReflectFriendDialogueTemplate
from .AReflectGoalDialogueTemplate import AReflectGoalDialogueTemplate
from .AReflectGoal2DialogueTemplate import AReflectGoal2DialogueTemplate
from .AReflectSuccessDialogueTemplate import AReflectSuccessDialogueTemplate
from .AReflectAchieveDialogueTemplate import AReflectAchieveDialogueTemplate


