import sys
sys.path.append('/home/jacky/Documents/GitHub/VHope')
from datetime import datetime
from src.dbo.user import DBOUser
from src.models.user import User
from src import Logger, IS_AFFIRM, IS_DENY, IS_END, UserHandler, DIALOGUE_TYPE_E_END, DIALOGUE_TYPE_RECOLLECTION, Pickle
from src.constants import *
from src.ORSEN import ORSEN
from src.textunderstanding.InputDecoder import InputDecoder
from VHope.FTER.FTER import FTER

from flask import request, session

orsen = ORSEN()
fter = FTER()
# Database access
dbo_user = DBOUser('users', User)

class VHope:
    def __init__(self):
        self.user_ID = session['id']
        self.user_name = session['username']

    def welcome(self):
        Logger.V_log("START: " + str(datetime.now()))
        print("J: USER ID= " + str(self.user_ID) + " USERNAME= " + self.user_name)

        if session['logged_in'] == True:
            print("J: Loggedin for the first time.")

            Logger.setup_loggers()
            orsen.initialize_story_prerequisites()
            orsen.world.reset_world()
            orsen.dialogue_planner.reset_new_world()

            user_log = str(self.user_ID) + " -> " + self.user_name
            Logger.V_log("USER: " + user_log)

            session['logged_in'] = False
        else:
            print("J: Not the first time.")


        if session['first'] == 1:
            welcome_msg = "Hello there, precious one. Welcome! I am VHope, an AI chatbot that will listen to your stories everyday and I will try my best to make you feel validated by giving empathetic responses. What do you want to talk about first?"
            Logger.V_log("EREN >> " + welcome_msg)
        else:
            welcome_msg = orsen.get_response(move_to_execute = orsen.dialogue_planner.get_welcome_message_type())

        # fter = FTER()
        # welcome_msg = fter.generate(welcome_msg)
        # Logger.V_log("FTER >> " + welcome_msg)
        
        session['history'] = welcome_msg

        return welcome_msg

    def get_input():
        userText = request.args.get('msg')
        return userText

    def get_response(self):
        
        usr_text = VHope.get_input()
        Logger.V_log("UTTERANCE >> " + usr_text)
        session['history'] = session['history'] + " eos " + usr_text
        print("J: USER=" + self.user_name + " TEXT= " + usr_text)

        response_text = orsen.get_response(usr_text)
        # response_text = orsen.get_response(usr_text, move_to_execute='c-pumping')

        # if with emotion, check well-being -- on ORSEN
        # if orsen.world.curr_emotion_event != None:
        #     Logger.V_log("EMOTION: " + orsen.world.curr_emotion_event.emotion)
        #     print("EMOTION TYPE " + str(type(orsen.world.curr_emotion_event.emotion)))

        # temporary fix for _comma_ generated by neural model
        if "_comma_" in response_text:
            response_text.replace("_comma_", ",")

        return response_text